name: Check conventions
on: [push]

jobs:

  emmocheck:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install EMMOntoPy
      run: |
        pip install --upgrade pip
        pip install EMMOntoPy

    - name: Check EMMO
      run: |
        emmocheck chameo.ttl
