name: Generate documentation
on: [push]

jobs:

  ontodoc:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc graphviz texlive-xetex texlive-xetex-extra
    - name: Install EMMOntoPy
      run: |
        pip install --upgrade pip
        pip install EMMOntoPy

    - name: Generate documentation
      run: |
        cd doc
        ontodoc --template=chameo.md --format=html ../chameo.ttl chameo.html
